name: account
services:
  mysql: # nome do serviça
    container_name: mysql # nome do container
    image: mysql:8.0.37
    ports:
      - 3306:3306
    networks:
      - private-network

networks:
  private-network:
    driver : bridge